version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
environment:
  matrix:
  - job_name: 32-bit Build
    platform: x86
  - job_name: 64-bit Build
    platform: x64
build:
  project: openssldir_check.sln
artifacts:
  - path: 'x64\Release\openssldir_check.exe'
    name: openssldir_check
  - path: 'Release\openssldir_check32.exe'
    name: openssldir_check32
