version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
  - platform: x86
  - platform: x64
build:
  project: openssldir_check.sln
artifacts:
  - path: 'x64\Release\openssldir_check.exe'
    name: openssldir_check
  - path: 'Release\openssldir_check32.exe'
    name: openssldir_check32
  - path: openssldir_check-%APPVEYOR_BUILD_VERSION%.zip
    name: openssldir_check-%APPVEYOR_BUILD_VERSION%
after_build:
   7z a openssldir_check-%APPVEYOR_BUILD_VERSION%.zip x64\Release\openssldir_check.exe Release\openssldir_check32.exe
