version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform:
  - x86
  - x64

build_script:
  - msbuild openssldir_check.sln /p:Configuration=Release /p:Platform=%PLATFORM%

artifacts:
  - path: 'x64\Release\openssldir_check.exe'
    name: openssldir_check64
    type: file
  - path: 'Release\openssldir_check.exe'
    name: openssldir_check32
    type: file
